'use strict';

/**
 * dart/enum — Style Dictionary custom format for Flutter.
 *
 * Outputs three sections in a single em_tokens.dart file:
 *
 *   1. Primitives (em-global)  — plain `static const Color/double/String`
 *   2. Semantic (em-theme)     — enum-keyed `Map<EmThemeMode, T>` for Light+Dark
 *   3. Component (everything else) — plain consts, sub-grouped by mode/variant
 *
 * Relies on the `flutter` transformGroup so `color/hex8flutter` has already
 * converted Figma RGBA floats to `0xAARRGGBB` strings by the time this runs.
 */
module.exports = function dartEnumFormat({ dictionary }) {
  const allTokens = dictionary.allTokens;

  // -------------------------------------------------------------------------
  // Categorise tokens by their source file (set by Style Dictionary from
  // the file path of each token's origin JSON).
  // -------------------------------------------------------------------------
  const primitiveTokens     = allTokens.filter(t => t.filePath?.includes('primitive'));
  const semanticLightTokens = allTokens.filter(t => t.filePath?.includes('semantic.light'));
  const darkTokens          = allTokens.filter(t => t.filePath?.includes('semantic.dark'));
  const componentTokens     = allTokens.filter(t => t.filePath?.includes('component'));

  // Dark token lookup keyed by path without the leading "dark" segment.
  // e.g. token.path = ['dark','background','primary'] → key = 'background.primary'
  const darkByPath = {};
  for (const t of darkTokens) {
    darkByPath[t.path.slice(1).join('.')] = t;
  }

  // -------------------------------------------------------------------------
  // Helpers
  // -------------------------------------------------------------------------

  /** "em-button-size" → "EmButtonSize", "background" → "EmBackground" */
  function toDartClass(segment) {
    const base = segment.startsWith('em-') ? segment.slice(3) : segment;
    const pascal = base
      .split(/[-_\s]+/)
      .map(s => s.charAt(0).toUpperCase() + s.slice(1))
      .join('');
    return `Em${pascal}`;
  }

  /**
   * Convert an array of path segments to a camelCase Dart identifier.
   * ['brand', 'bash', '500'] → 'brandBash500'
   * ['grid-xsm', 'min-width'] → 'gridXsmMinWidth'
   */
  function toCamel(segments) {
    const parts = segments.join('-').split(/[-_]+/);
    return parts
      .map((s, i) => (i === 0 ? s : s.charAt(0).toUpperCase() + s.slice(1)))
      .join('');
  }

  /**
   * Return the Dart type name for a token value.
   * color hex strings → 'Color', numbers → 'double', strings → 'String', booleans → 'bool'
   */
  function isColorVal(val) {
    return typeof val === 'string' && (val.startsWith('0x') || val.startsWith('Color('));
  }

  function dartType(token) {
    const val = token.$value;
    if (isColorVal(val)) return 'Color';
    if (typeof val === 'number') return 'double';
    if (typeof val === 'boolean') return 'bool';
    return 'String';
  }

  /**
   * Format a single resolved token value as a Dart literal.
   * The flutter transformGroup may produce either:
   *   '0xFF7474EE'         → Color(0xFF7474EE)
   *   'Color(0xFF7474EE)'  → Color(0xFF7474EE)  (already formatted)
   * - 16   → '16.0'
   * - 'Inter' → "'Inter'"
   */
  function dartLiteral(token) {
    const val = token.$value;
    if (typeof val === 'string' && val.startsWith('Color(')) return val;
    if (typeof val === 'string' && val.startsWith('0x')) return `Color(${val})`;
    if (typeof val === 'number') return Number.isInteger(val) ? `${val}.0` : String(val);
    if (typeof val === 'boolean') return String(val);
    return `'${val}'`;
  }

  /**
   * Group an array of tokens by their first path segment.
   * Returns an ordered Map so iteration order matches insertion order.
   */
  function groupBy(tokens, keyFn) {
    const map = new Map();
    for (const t of tokens) {
      const key = keyFn(t);
      if (!map.has(key)) map.set(key, []);
      map.get(key).push(t);
    }
    return map;
  }

  // -------------------------------------------------------------------------
  // Section builders
  // -------------------------------------------------------------------------

  const lines = [];

  function section(title) {
    lines.push('');
    lines.push(`// ${'─'.repeat(65)}`);
    lines.push(`// ${title}`);
    lines.push(`// ${'─'.repeat(65)}`);
    lines.push('');
  }

  // ── File header ────────────────────────────────────────────────────────────
  lines.push('// Generated by elementa-token-pipeline — DO NOT EDIT.');
  lines.push('// Run `npm run sync` to regenerate from Figma.');
  lines.push('');
  lines.push("import 'package:flutter/material.dart';");
  lines.push('');
  lines.push('/// Selects between Light and Dark semantic token values.');
  lines.push('enum EmThemeMode { light, dark }');

  // ── Primitives ─────────────────────────────────────────────────────────────
  // Grouped by path[0] (always 'colour' for em-global ramps).
  section('Primitives');

  const primitiveGroups = groupBy(primitiveTokens, t => t.path[0]);
  for (const [cat, tokens] of primitiveGroups) {
    lines.push(`class ${toDartClass(cat)} {`);
    for (const t of tokens) {
      const prop = toCamel(t.path.slice(1));
      const type = dartType(t);
      const val  = dartLiteral(t);
      lines.push(`  static const ${type} ${prop} = ${val};`);
    }
    lines.push('}');
    lines.push('');
  }

  // ── Semantic (Light / Dark) ────────────────────────────────────────────────
  section('Semantic  (Light / Dark)');

  const semanticGroups = groupBy(semanticLightTokens, t => t.path[0]);
  for (const [cat, tokens] of semanticGroups) {
    lines.push(`class ${toDartClass(cat)} {`);
    for (const t of tokens) {
      const propPath = t.path; // e.g. ['background', 'primary']
      const prop     = toCamel(propPath.slice(1));
      const lookupKey = propPath.join('.');  // matches darkByPath keys
      const darkToken = darkByPath[lookupKey];

      if (darkToken) {
        // Emit an enum-keyed map
        const type     = dartType(t);
        const lightVal = dartLiteral(t);
        const darkVal  = dartLiteral(darkToken);
        lines.push(`  static const Map<EmThemeMode, ${type}> ${prop} = {`);
        lines.push(`    EmThemeMode.light: ${lightVal},`);
        lines.push(`    EmThemeMode.dark:  ${darkVal},`);
        lines.push(`  };`);
      } else {
        // No dark counterpart — plain const
        const type = dartType(t);
        const val  = dartLiteral(t);
        lines.push(`  static const ${type} ${prop} = ${val};`);
      }
    }
    lines.push('}');
    lines.push('');
  }

  // ── Component ──────────────────────────────────────────────────────────────
  section('Component');

  // Group by collection (path[0]), then by mode (path[1]) within each collection.
  const componentGroups = groupBy(componentTokens, t => t.path[0]);
  for (const [collectionName, tokens] of componentGroups) {
    lines.push(`class ${toDartClass(collectionName)} {`);

    // Check if this collection uses a mode sub-namespace (path.length > 2)
    const isMultiMode = tokens.some(t => t.path.length > 2);

    if (isMultiMode) {
      const byMode = groupBy(tokens, t => t.path[1]);
      for (const [mode, modeTokens] of byMode) {
        lines.push(`  // ${mode}`);
        for (const t of modeTokens) {
          const prop = toCamel([mode, ...t.path.slice(2)]);
          const type = dartType(t);
          const val  = dartLiteral(t);
          lines.push(`  static const ${type} ${prop} = ${val};`);
        }
      }
    } else {
      for (const t of tokens) {
        const prop = toCamel(t.path.slice(1));
        const type = dartType(t);
        const val  = dartLiteral(t);
        lines.push(`  static const ${type} ${prop} = ${val};`);
      }
    }

    lines.push('}');
    lines.push('');
  }

  return lines.join('\n');
};
